
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schema.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _Add
        {
            WS_FIELD_DESCRIPTION x;
            WS_FIELD_DESCRIPTION y;
            WS_FIELD_DESCRIPTION* _AddFields [2]; 
        } _Adddescs; // end of _Add
        struct // _AddResponse
        {
            WS_FIELD_DESCRIPTION AddResult;
            WS_FIELD_DESCRIPTION* _AddResponseFields [1]; 
        } _AddResponsedescs; // end of _AddResponse
        struct // _GetAllXYResponse
        {
            WS_FIELD_DESCRIPTION GetAllXYResult;
            WS_FIELD_DESCRIPTION* _GetAllXYResponseFields [1]; 
        } _GetAllXYResponsedescs; // end of _GetAllXYResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _AddTypeName;  // Add
            WS_XML_STRING _AddTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _AddxLocalName;  // x
            WS_XML_STRING _AddyLocalName;  // y
            WS_XML_STRING _AddResponseTypeName;  // AddResponse
            WS_XML_STRING _AddResponseAddResultLocalName;  // AddResult
            WS_XML_STRING _GetAllXYTypeName;  // GetAllXY
            WS_XML_STRING _GetAllXYResponseTypeName;  // GetAllXYResponse
            WS_XML_STRING _GetAllXYResponseGetAllXYResultLocalName;  // No
            WS_XML_STRING _GetAllXYResponseGetAllXYResultNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING _GetAllXYResponseGetAllXYResultWrapperName;  // GetAllXYResult
            WS_XML_STRING _DoWorkTypeName;  // DoWork
            WS_XML_STRING _DoWorkResponseTypeName;  // DoWorkResponse
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _Add
            { // field description for x
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddxLocalName, // x
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, x),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for x
            { // field description for y
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddyLocalName, // y
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, y),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for y
            {    // fields description for _Add
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.x,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.y,
            },
        },    // _Add
        {   // _AddResponse
            { // field description for AddResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseAddResultLocalName, // AddResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddResponse, AddResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for AddResult
            {    // fields description for _AddResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs.AddResult,
            },
        },    // _AddResponse
        {   // _GetAllXYResponse
            { // field description for GetAllXYResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultWrapperName, // GetAllXYResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.No,
            WsOffsetOf(_GetAllXYResponse, GetAllXYResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_GetAllXYResponse, GetAllXYResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultLocalName, // No
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for GetAllXYResult
            {    // fields description for _GetAllXYResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs.GetAllXYResult,
            },
        },    // _GetAllXYResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Add",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("x",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("y",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("AddResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("AddResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXY",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXYResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("No",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXYResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("DoWork",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("DoWorkResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
        },  // end of xmlStrings
        
        {   // tempuri_org_xsddictionary
        // d16f8e63-e9f0-455d-9248-845403478a11 
        { 0xd16f8e63, 0xe9f0, 0x455d, { 0x92, 0x48, 0x84,0x54, 0x03, 0x47, 0x8a, 0x11 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        13,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.Add,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.AddResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYTypeName, // GetAllXY
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllXY,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseTypeName, // GetAllXYResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllXYResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWork,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWorkResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_Add),
        __alignof(_Add),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _Add
        {
        sizeof(_AddResponse),
        __alignof(_AddResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _AddResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYTypeName, // GetAllXY
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllXY
        {
        sizeof(_GetAllXYResponse),
        __alignof(_GetAllXYResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs._GetAllXYResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs._GetAllXYResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseTypeName, // GetAllXYResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllXYResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWork
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWorkResponse
    }, // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
