
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"

typedef struct _schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct // ArrayOfanyType
        {
            WS_FIELD_DESCRIPTION anyType;
            WS_FIELD_DESCRIPTION* ArrayOfanyTypeFields [1]; 
        } ArrayOfanyTypedescs; // end of ArrayOfanyType
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING ArrayOfanyTypeTypeName;  // ArrayOfanyType
            WS_XML_STRING ArrayOfanyTypeTypeNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            WS_XML_STRING ArrayOfanyTypeanyTypeLocalName;  // anyType
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions;

const static _schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions =
{
    { // global types
        0,
        {   // ArrayOfanyType
            { // field description for anyType
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_XML_BUFFER_TYPE,
            0,
            WsOffsetOf(ArrayOfanyType, anyType),
             WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfanyType, anyTypeCount),
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfanyTypeanyTypeLocalName, // anyType
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfanyTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            0,
            },    // end of field description for anyType
            {    // fields description for ArrayOfanyType
            (WS_FIELD_DESCRIPTION*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.globalTypes.ArrayOfanyTypedescs.anyType,
            },
        },    // ArrayOfanyType
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfanyType",&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/Arrays",&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("anyType",&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.dict, 2),
        },  // end of xmlStrings
        
        {   // schemas_microsoft_com_2003_10_Serialization_Arrays_xsddictionary
        // 78e5f7cc-e8a5-43f0-9d28-23016c20e9f7 
        { 0x78e5f7cc, 0xe8a5, 0x43f0, { 0x9d, 0x28, 0x23,0x01, 0x6c, 0x20, 0xe9, 0xf7 } },
        (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.xmlStrings,
        3,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions

const _schemas_microsoft_com_2003_10_Serialization_Arrays_xsd schemas_microsoft_com_2003_10_Serialization_Arrays_xsd =
{
    {// globalTypes
        {
        sizeof(ArrayOfanyType),
        __alignof(ArrayOfanyType),
        (WS_FIELD_DESCRIPTION**)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.globalTypes.ArrayOfanyTypedescs.ArrayOfanyTypeFields,
        WsCountOf(schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.globalTypes.ArrayOfanyTypedescs.ArrayOfanyTypeFields),
        (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfanyTypeTypeName, // ArrayOfanyType
        (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfanyTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
        0,
        0,
        0,
        },   // end of struct description for ArrayOfanyType
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfanyTypeTypeName, // ArrayOfanyType
            (WS_XML_STRING*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfanyTypeTypeNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            WS_STRUCT_TYPE,
            (void*)&schemas_microsoft_com_2003_10_Serialization_Arrays_xsd.globalTypes.ArrayOfanyType,
        },
    }, // globalElements
}; // end of _schemas_microsoft_com_2003_10_Serialization_Arrays_xsd
