
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
#include "schema.xsd.h"

typedef struct _schema_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct // ArrayOfNoBD
        {
            struct // NoBD
            {
                WS_FIELD_DESCRIPTION avatar3d;
                WS_FIELD_DESCRIPTION humor;
                WS_FIELD_DESCRIPTION id;
                WS_FIELD_DESCRIPTION nome;
                WS_FIELD_DESCRIPTION ntag;
                WS_FIELD_DESCRIPTION x;
                WS_FIELD_DESCRIPTION y;
                WS_FIELD_DESCRIPTION* NoBDFields [7]; 
            } NoBDdescs; // end of NoBD
            WS_FIELD_DESCRIPTION NoBD;
            WS_FIELD_DESCRIPTION* ArrayOfNoBDFields [1]; 
        } ArrayOfNoBDdescs; // end of ArrayOfNoBD
        struct // ArrayOfArcoBD
        {
            struct // ArcoBD
            {
                WS_FIELD_DESCRIPTION forca;
                WS_FIELD_DESCRIPTION idPrim;
                WS_FIELD_DESCRIPTION idRel;
                WS_FIELD_DESCRIPTION idSec;
                WS_FIELD_DESCRIPTION* ArcoBDFields [4]; 
            } ArcoBDdescs; // end of ArcoBD
            WS_FIELD_DESCRIPTION ArcoBD;
            WS_FIELD_DESCRIPTION* ArrayOfArcoBDFields [1]; 
        } ArrayOfArcoBDdescs; // end of ArrayOfArcoBD
        struct // Utilizador
        {
            WS_FIELD_DESCRIPTION avatar;
            WS_FIELD_DESCRIPTION morada;
            WS_FIELD_DESCRIPTION nasc;
            WS_FIELD_DESCRIPTION nick;
            WS_FIELD_DESCRIPTION nome;
            WS_FIELD_DESCRIPTION tele;
            WS_FIELD_DESCRIPTION* UtilizadorFields [6]; 
        } Utilizadordescs; // end of Utilizador
        struct // Ligacao
        {
            WS_FIELD_DESCRIPTION id1;
            WS_FIELD_DESCRIPTION id2;
            WS_FIELD_DESCRIPTION tags;
            WS_FIELD_DESCRIPTION* LigacaoFields [3]; 
        } Ligacaodescs; // end of Ligacao
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING ArrayOfNoBDTypeName;  // ArrayOfNoBD
            WS_XML_STRING ArrayOfNoBDTypeNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING NoBDTypeName;  // NoBD
            WS_XML_STRING NoBDavatar3dLocalName;  // avatar3d
            WS_XML_STRING NoBDhumorLocalName;  // humor
            WS_XML_STRING NoBDidLocalName;  // id
            WS_XML_STRING NoBDnomeLocalName;  // nome
            WS_XML_STRING NoBDntagLocalName;  // ntag
            WS_XML_STRING NoBDxLocalName;  // x
            WS_XML_STRING NoBDyLocalName;  // y
            WS_XML_STRING ArrayOfArcoBDTypeName;  // ArrayOfArcoBD
            WS_XML_STRING ArcoBDTypeName;  // ArcoBD
            WS_XML_STRING ArcoBDforcaLocalName;  // forca
            WS_XML_STRING ArcoBDidPrimLocalName;  // idPrim
            WS_XML_STRING ArcoBDidRelLocalName;  // idRel
            WS_XML_STRING ArcoBDidSecLocalName;  // idSec
            WS_XML_STRING UtilizadorTypeName;  // Utilizador
            WS_XML_STRING UtilizadoravatarLocalName;  // avatar
            WS_XML_STRING UtilizadormoradaLocalName;  // morada
            WS_XML_STRING UtilizadornascLocalName;  // nasc
            WS_XML_STRING UtilizadornickLocalName;  // nick
            WS_XML_STRING UtilizadorteleLocalName;  // tele
            WS_XML_STRING LigacaoTypeName;  // Ligacao
            WS_XML_STRING Ligacaoid1LocalName;  // id1
            WS_XML_STRING Ligacaoid2LocalName;  // id2
            WS_XML_STRING LigacaotagsLocalName;  // string
            WS_XML_STRING LigacaotagsNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            WS_XML_STRING LigacaotagsWrapperName;  // tags
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _schema_xsdLocalDefinitions;

const static _schema_xsdLocalDefinitions schema_xsdLocalDefinitions =
{
    { // global types
        0,
        {   // ArrayOfNoBD
            {   // NoBD
                { // field description for avatar3d
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDavatar3dLocalName, // avatar3d
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(NoBD, avatar3d),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for avatar3d
                { // field description for humor
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDhumorLocalName, // humor
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(NoBD, humor),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for humor
                { // field description for id
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDidLocalName, // id
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(NoBD, id),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for id
                { // field description for nome
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDnomeLocalName, // nome
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_WSZ_TYPE,
                0,
                WsOffsetOf(NoBD, nome),
                 WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
                0,
                0xffffffff
                },    // end of field description for nome
                { // field description for ntag
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDntagLocalName, // ntag
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(NoBD, ntag),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for ntag
                { // field description for x
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDxLocalName, // x
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(NoBD, x),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for x
                { // field description for y
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDyLocalName, // y
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(NoBD, y),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for y
                {    // fields description for NoBD
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.avatar3d,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.humor,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.id,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.nome,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.ntag,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.x,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.y,
                },
            },    // NoBD
            { // field description for NoBD
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.NoBD,
            WsOffsetOf(ArrayOfNoBD, NoBD),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfNoBD, NoBDCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDTypeName, // NoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for NoBD
            {    // fields description for ArrayOfNoBD
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBD,
            },
        },    // ArrayOfNoBD
        {   // ArrayOfArcoBD
            {   // ArcoBD
                { // field description for forca
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDforcaLocalName, // forca
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, forca),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for forca
                { // field description for idPrim
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDidPrimLocalName, // idPrim
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, idPrim),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for idPrim
                { // field description for idRel
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDidRelLocalName, // idRel
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, idRel),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for idRel
                { // field description for idSec
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDidSecLocalName, // idSec
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, idSec),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for idSec
                {    // fields description for ArcoBD
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.forca,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.idPrim,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.idRel,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.idSec,
                },
            },    // ArcoBD
            { // field description for ArcoBD
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArcoBD,
            WsOffsetOf(ArrayOfArcoBD, ArcoBD),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfArcoBD, ArcoBDCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDTypeName, // ArcoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for ArcoBD
            {    // fields description for ArrayOfArcoBD
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBD,
            },
        },    // ArrayOfArcoBD
        {   // Utilizador
            { // field description for avatar
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UtilizadoravatarLocalName, // avatar
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Utilizador, avatar),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for avatar
            { // field description for morada
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UtilizadormoradaLocalName, // morada
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Utilizador, morada),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for morada
            { // field description for nasc
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UtilizadornascLocalName, // nasc
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Utilizador, nasc),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for nasc
            { // field description for nick
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UtilizadornickLocalName, // nick
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Utilizador, nick),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for nick
            { // field description for nome
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDnomeLocalName, // nome
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Utilizador, nome),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for nome
            { // field description for tele
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UtilizadorteleLocalName, // tele
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(Utilizador, tele),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for tele
            {    // fields description for Utilizador
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.avatar,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.morada,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.nasc,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.nick,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.nome,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.tele,
            },
        },    // Utilizador
        {   // Ligacao
            { // field description for id1
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.Ligacaoid1LocalName, // id1
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(Ligacao, id1),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id1
            { // field description for id2
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.Ligacaoid2LocalName, // id2
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(Ligacao, id2),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id2
            { // field description for tags
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaotagsWrapperName, // tags
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(Ligacao, tags),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(Ligacao, tagsCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaotagsLocalName, // string
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaotagsNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            0,
            },    // end of field description for tags
            {    // fields description for Ligacao
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Ligacaodescs.id1,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Ligacaodescs.id2,
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.Ligacaodescs.tags,
            },
        },    // Ligacao
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfNoBD",&schema_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&schema_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("NoBD",&schema_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("avatar3d",&schema_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("humor",&schema_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("id",&schema_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("nome",&schema_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("ntag",&schema_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("x",&schema_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("y",&schema_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfArcoBD",&schema_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("ArcoBD",&schema_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("forca",&schema_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("idPrim",&schema_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("idRel",&schema_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("idSec",&schema_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("Utilizador",&schema_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("avatar",&schema_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("morada",&schema_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("nasc",&schema_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("nick",&schema_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("tele",&schema_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("Ligacao",&schema_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("id1",&schema_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("id2",&schema_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("string",&schema_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/Arrays",&schema_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("tags",&schema_xsdLocalDefinitions.dictionary.dict, 27),
        },  // end of xmlStrings
        
        {   // schema_xsddictionary
        // b3dc2056-cb46-46f6-800a-ef510fce08ca 
        { 0xb3dc2056, 0xcb46, 0x46f6, { 0x80, 0x0a, 0xef,0x51, 0x0f, 0xce, 0x08, 0xca } },
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings,
        28,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of schema_xsdLocalDefinitions

const _schema_xsd schema_xsd =
{
    {// globalTypes
        {
        sizeof(ArrayOfNoBD),
        __alignof(ArrayOfNoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.ArrayOfNoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.ArrayOfNoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeName, // ArrayOfNoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArrayOfNoBD
        {
        sizeof(NoBD),
        __alignof(NoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.NoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.NoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDTypeName, // NoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for NoBD
        {
        sizeof(ArrayOfArcoBD),
        __alignof(ArrayOfArcoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArrayOfArcoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArrayOfArcoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfArcoBDTypeName, // ArrayOfArcoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArrayOfArcoBD
        {
        sizeof(ArcoBD),
        __alignof(ArcoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.ArcoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.ArcoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDTypeName, // ArcoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArcoBD
        {
        sizeof(Utilizador),
        __alignof(Utilizador),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.UtilizadorFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.Utilizadordescs.UtilizadorFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UtilizadorTypeName, // Utilizador
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for Utilizador
        {
        sizeof(Ligacao),
        __alignof(Ligacao),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.Ligacaodescs.LigacaoFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.Ligacaodescs.LigacaoFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoTypeName, // Ligacao
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for Ligacao
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeName, // ArrayOfNoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArrayOfNoBD,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDTypeName, // NoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.NoBD,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfArcoBDTypeName, // ArrayOfArcoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArrayOfArcoBD,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDTypeName, // ArcoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArcoBD,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.UtilizadorTypeName, // Utilizador
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Utilizador,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.LigacaoTypeName, // Ligacao
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Ligacao,
        },
    }, // globalElements
}; // end of _schema_xsd
