
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schema.xsd.h"

typedef struct _schema_xsdLocalDefinitions 
{
    struct  // global types
    {
        char unused;
        struct // ArrayOfNoBD
        {
            struct // NoBD
            {
                WS_FIELD_DESCRIPTION id;
                WS_FIELD_DESCRIPTION x;
                WS_FIELD_DESCRIPTION y;
                WS_FIELD_DESCRIPTION* NoBDFields [3]; 
            } NoBDdescs; // end of NoBD
            WS_FIELD_DESCRIPTION NoBD;
            WS_FIELD_DESCRIPTION* ArrayOfNoBDFields [1]; 
        } ArrayOfNoBDdescs; // end of ArrayOfNoBD
        struct // ArrayOfArcoBD
        {
            struct // ArcoBD
            {
                WS_FIELD_DESCRIPTION forca;
                WS_FIELD_DESCRIPTION idPrim;
                WS_FIELD_DESCRIPTION idRel;
                WS_FIELD_DESCRIPTION idSec;
                WS_FIELD_DESCRIPTION* ArcoBDFields [4]; 
            } ArcoBDdescs; // end of ArcoBD
            WS_FIELD_DESCRIPTION ArcoBD;
            WS_FIELD_DESCRIPTION* ArrayOfArcoBDFields [1]; 
        } ArrayOfArcoBDdescs; // end of ArrayOfArcoBD
    } globalTypes;  // end of global types
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING ArrayOfNoBDTypeName;  // ArrayOfNoBD
            WS_XML_STRING ArrayOfNoBDTypeNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING NoBDTypeName;  // NoBD
            WS_XML_STRING NoBDidLocalName;  // id
            WS_XML_STRING NoBDxLocalName;  // x
            WS_XML_STRING NoBDyLocalName;  // y
            WS_XML_STRING ArrayOfArcoBDTypeName;  // ArrayOfArcoBD
            WS_XML_STRING ArcoBDTypeName;  // ArcoBD
            WS_XML_STRING ArcoBDforcaLocalName;  // forca
            WS_XML_STRING ArcoBDidPrimLocalName;  // idPrim
            WS_XML_STRING ArcoBDidRelLocalName;  // idRel
            WS_XML_STRING ArcoBDidSecLocalName;  // idSec
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _schema_xsdLocalDefinitions;

const static _schema_xsdLocalDefinitions schema_xsdLocalDefinitions =
{
    { // global types
        0,
        {   // ArrayOfNoBD
            {   // NoBD
                { // field description for id
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDidLocalName, // id
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(NoBD, id),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for id
                { // field description for x
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDxLocalName, // x
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(NoBD, x),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for x
                { // field description for y
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDyLocalName, // y
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(NoBD, y),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for y
                {    // fields description for NoBD
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.id,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.x,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.y,
                },
            },    // NoBD
            { // field description for NoBD
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.NoBD,
            WsOffsetOf(ArrayOfNoBD, NoBD),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfNoBD, NoBDCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDTypeName, // NoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for NoBD
            {    // fields description for ArrayOfNoBD
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBD,
            },
        },    // ArrayOfNoBD
        {   // ArrayOfArcoBD
            {   // ArcoBD
                { // field description for forca
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDforcaLocalName, // forca
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, forca),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for forca
                { // field description for idPrim
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDidPrimLocalName, // idPrim
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, idPrim),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for idPrim
                { // field description for idRel
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDidRelLocalName, // idRel
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, idRel),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for idRel
                { // field description for idSec
                WS_ELEMENT_FIELD_MAPPING,
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDidSecLocalName, // idSec
                (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
                WS_INT32_TYPE,
                0,
                WsOffsetOf(ArcoBD, idSec),
                 WS_FIELD_OPTIONAL,
                0,
                0xffffffff
                },    // end of field description for idSec
                {    // fields description for ArcoBD
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.forca,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.idPrim,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.idRel,
                (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.idSec,
                },
            },    // ArcoBD
            { // field description for ArcoBD
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            0,
            0,
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArcoBD,
            WsOffsetOf(ArrayOfArcoBD, ArcoBD),
            WS_FIELD_POINTER| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(ArrayOfArcoBD, ArcoBDCount),
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDTypeName, // ArcoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for ArcoBD
            {    // fields description for ArrayOfArcoBD
            (WS_FIELD_DESCRIPTION*)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBD,
            },
        },    // ArrayOfArcoBD
    }, // end of global types
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfNoBD",&schema_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&schema_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("NoBD",&schema_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("id",&schema_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("x",&schema_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("y",&schema_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("ArrayOfArcoBD",&schema_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("ArcoBD",&schema_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("forca",&schema_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("idPrim",&schema_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("idRel",&schema_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("idSec",&schema_xsdLocalDefinitions.dictionary.dict, 11),
        },  // end of xmlStrings
        
        {   // schema_xsddictionary
        // 8206cb95-463c-473f-9ca3-35096812371a 
        { 0x8206cb95, 0x463c, 0x473f, { 0x9c, 0xa3, 0x35,0x09, 0x68, 0x12, 0x37, 0x1a } },
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings,
        12,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of schema_xsdLocalDefinitions

const _schema_xsd schema_xsd =
{
    {// globalTypes
        {
        sizeof(ArrayOfNoBD),
        __alignof(ArrayOfNoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.ArrayOfNoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.ArrayOfNoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeName, // ArrayOfNoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArrayOfNoBD
        {
        sizeof(NoBD),
        __alignof(NoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.NoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfNoBDdescs.NoBDdescs.NoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDTypeName, // NoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for NoBD
        {
        sizeof(ArrayOfArcoBD),
        __alignof(ArrayOfArcoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArrayOfArcoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArrayOfArcoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfArcoBDTypeName, // ArrayOfArcoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArrayOfArcoBD
        {
        sizeof(ArcoBD),
        __alignof(ArcoBD),
        (WS_FIELD_DESCRIPTION**)&schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.ArcoBDFields,
        WsCountOf(schema_xsdLocalDefinitions.globalTypes.ArrayOfArcoBDdescs.ArcoBDdescs.ArcoBDFields),
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDTypeName, // ArcoBD
        (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
        0,
        0,
        0,
        },   // end of struct description for ArcoBD
    }, // globalTypes
    {// globalElements
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeName, // ArrayOfNoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArrayOfNoBD,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.NoBDTypeName, // NoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.NoBD,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfArcoBDTypeName, // ArrayOfArcoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArrayOfArcoBD,
        },
        {
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArcoBDTypeName, // ArcoBD
            (WS_XML_STRING*)&schema_xsdLocalDefinitions.dictionary.xmlStrings.ArrayOfNoBDTypeNamespace, // http://schemas.datacontract.org/2004/07/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArcoBD,
        },
    }, // globalElements
}; // end of _schema_xsd
