
// File generated by Wsutil Compiler version 1.0092 
// This file defines C/C++ functions, callbacks, types that correspond to operations,
// and types specified in WSDL and XSD files processed by WsUtil compiler. The generated 
// type definitions, function and callback declarations can be used with various 
// Web Services APIs either in applications that send and receive requests to and 
// from a running web service, or in the implementation of web services, or in both. 
//
// If Wsutil has generated this file from an XSD file, the file contains definition of 
// C/C++ structures types that correspond to types defined in the XSD file. 
// For example, if the following XSD complexType is defined in the XSD file
//
//      <xsd:complexType name="AddRequest">
//          <xsd:sequence>
//              <xsd:element minOccurs="0" name="a" type="xsd:int" />
//              <xsd:element minOccurs="0" name="b" type="xsd:int" />
//          </xsd:sequence>
//      </xsd:complexType>
// 
// this file contains the following definitions of the structure 
//      // AddRequest (xsd:complexType)
//      // <AddRequest xmlns='http://tempuri.org'>
//      // WS_STRUCT_DESCRIPTION* = &calculator_xsd.globalTypes.AddRequest
//      struct AddRequest
//      {
//          int a;
//          int b;
//      };
//
// For more information on how to use the C/C++ types generated in this file to read or write elements of XML documents that conform to 
// this XSD, please see the documentation for 
// WsReadType() and WsWriteType() functions.
// 
#if _MSC_VER > 1000 
#pragma once
#endif

#ifdef __cplusplus
extern "C" {
#endif

// The following types were generated:

//     struct _Add;
//     struct _AddResponse;
//     struct _GetAllXY;
//     struct _GetAllXYResponse;
//     struct _GetAllArcoBD;
//     struct _GetAllArcoBDResponse;
//     struct _GetUtilizadorByID;
//     struct _GetUtilizadorByIDResponse;
//     struct _GetTagsByUserID;
//     struct _GetTagsByUserIDResponse;
//     struct _GetHumorByUserID;
//     struct _GetHumorByUserIDResponse;
//     struct _getMenorCaminho;
//     struct _getMenorCaminhoResponse;
//     struct _getCaminhoForte;
//     struct _getCaminhoForteResponse;
//     struct _DoWork;
//     struct _DoWorkResponse;
//     struct _validateLogin;
//     struct _validateLoginResponse;
//     struct _xTagsEmComum;
//     struct _xTagsEmComumResponse;
//     struct _tamanhoRedeUtilizador;
//     struct _tamanhoRedeUtilizadorResponse;
//     struct _sugereAmigos;
//     struct _sugereAmigosResponse;
//     struct _grafoAmigosComuns;
//     struct _grafoAmigosComunsResponse;
//     struct _getLigacao;
//     struct _getLigacaoResponse;
//     struct _getAmigosNivel3;
//     struct _getAmigosNivel3Response;
//     struct _getMavenOfTag;
//     struct _getMavenOfTagResponse;
//     struct _getSeparacao;
//     struct _getSeparacaoResponse;
//     struct _getGrafoNivel3;
//     struct _getGrafoNivel3Response;
//     struct _getNosGrafoAmigos;
//     struct _getNosGrafoAmigosResponse;
//     struct _getNosGrafo;
//     struct _getNosGrafoResponse;

// The following header files must be included in this order before this one

// #include <WebServices.h>
// #include "schema.xsd.h"
// #include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"

////////////////////////////////////////////////
// C structure definitions for generated types
////////////////////////////////////////////////

// typeDescription: n/a
typedef struct _Add 
{
    int x;
    int y;
} _Add;

// typeDescription: n/a
typedef struct _AddResponse 
{
    int AddResult;
} _AddResponse;

typedef struct _GetAllXY _GetAllXY;

// typeDescription: n/a
typedef struct _GetAllXYResponse 
{
    unsigned int GetAllXYResultCount;
    __field_ecount_opt(GetAllXYResultCount)struct NoBD** GetAllXYResult; // optional
} _GetAllXYResponse;

typedef struct _GetAllArcoBD _GetAllArcoBD;

// typeDescription: n/a
typedef struct _GetAllArcoBDResponse 
{
    unsigned int GetAllArcoBDResultCount;
    __field_ecount_opt(GetAllArcoBDResultCount)struct ArcoBD** GetAllArcoBDResult; // optional
} _GetAllArcoBDResponse;

// typeDescription: n/a
typedef struct _GetUtilizadorByID 
{
    int uid;
} _GetUtilizadorByID;

// typeDescription: n/a
typedef struct _GetUtilizadorByIDResponse 
{
    struct Utilizador* GetUtilizadorByIDResult; // optional
} _GetUtilizadorByIDResponse;

// typeDescription: n/a
typedef struct _GetTagsByUserID 
{
    int uid;
} _GetTagsByUserID;

// typeDescription: n/a
typedef struct _GetTagsByUserIDResponse 
{
    unsigned int GetTagsByUserIDResultCount;
    __field_ecount_opt(GetTagsByUserIDResultCount)WCHAR** GetTagsByUserIDResult; // optional
} _GetTagsByUserIDResponse;

// typeDescription: n/a
typedef struct _GetHumorByUserID 
{
    int uid;
} _GetHumorByUserID;

// typeDescription: n/a
typedef struct _GetHumorByUserIDResponse 
{
    WCHAR* GetHumorByUserIDResult; // optional
} _GetHumorByUserIDResponse;

// typeDescription: n/a
typedef struct _getMenorCaminho 
{
    int no1;
    int no2;
} _getMenorCaminho;

// typeDescription: n/a
typedef struct _getMenorCaminhoResponse 
{
    WCHAR* getMenorCaminhoResult; // optional
} _getMenorCaminhoResponse;

// typeDescription: n/a
typedef struct _getCaminhoForte 
{
    int no1;
    int no2;
} _getCaminhoForte;

// typeDescription: n/a
typedef struct _getCaminhoForteResponse 
{
    WCHAR* getCaminhoForteResult; // optional
} _getCaminhoForteResponse;

typedef struct _DoWork _DoWork;

typedef struct _DoWorkResponse _DoWorkResponse;

// typeDescription: n/a
typedef struct _validateLogin 
{
    WCHAR* userName; // optional
    WCHAR* password; // optional
} _validateLogin;

// typeDescription: n/a
typedef struct _validateLoginResponse 
{
    int validateLoginResult;
} _validateLoginResponse;

// typeDescription: n/a
typedef struct _xTagsEmComum 
{
    int id;
    int n;
} _xTagsEmComum;

// typeDescription: n/a
typedef struct _xTagsEmComumResponse 
{
    WCHAR* xTagsEmComumResult; // optional
} _xTagsEmComumResponse;

// typeDescription: n/a
typedef struct _tamanhoRedeUtilizador 
{
    int id;
} _tamanhoRedeUtilizador;

// typeDescription: n/a
typedef struct _tamanhoRedeUtilizadorResponse 
{
    int tamanhoRedeUtilizadorResult;
} _tamanhoRedeUtilizadorResponse;

// typeDescription: n/a
typedef struct _sugereAmigos 
{
    int id;
} _sugereAmigos;

// typeDescription: n/a
typedef struct _sugereAmigosResponse 
{
    WCHAR* sugereAmigosResult; // optional
} _sugereAmigosResponse;

// typeDescription: n/a
typedef struct _grafoAmigosComuns 
{
    int user1;
    int user2;
} _grafoAmigosComuns;

// typeDescription: n/a
typedef struct _grafoAmigosComunsResponse 
{
    WCHAR* grafoAmigosComunsResult; // optional
} _grafoAmigosComunsResponse;

// typeDescription: n/a
typedef struct _getLigacao 
{
    int userreg;
    int user1;
    int user2;
} _getLigacao;

// typeDescription: n/a
typedef struct _getLigacaoResponse 
{
    struct Ligacao* getLigacaoResult; // optional
} _getLigacaoResponse;

// typeDescription: n/a
typedef struct _getAmigosNivel3 
{
    int userID;
} _getAmigosNivel3;

// typeDescription: n/a
typedef struct _getAmigosNivel3Response 
{
    WCHAR* getAmigosNivel3Result; // optional
} _getAmigosNivel3Response;

// typeDescription: n/a
typedef struct _getMavenOfTag 
{
    WCHAR* tag; // optional
} _getMavenOfTag;

// typeDescription: n/a
typedef struct _getMavenOfTagResponse 
{
    WCHAR* getMavenOfTagResult; // optional
} _getMavenOfTagResponse;

// typeDescription: n/a
typedef struct _getSeparacao 
{
    int no1;
    int no2;
} _getSeparacao;

// typeDescription: n/a
typedef struct _getSeparacaoResponse 
{
    WCHAR* getSeparacaoResult; // optional
} _getSeparacaoResponse;

// typeDescription: n/a
typedef struct _getGrafoNivel3 
{
    int userid;
} _getGrafoNivel3;

// typeDescription: n/a
typedef struct _getGrafoNivel3Response 
{
    unsigned int getGrafoNivel3ResultCount;
    __field_ecount_opt(getGrafoNivel3ResultCount)struct NoBD** getGrafoNivel3Result; // optional
} _getGrafoNivel3Response;

// typeDescription: n/a
typedef struct _getNosGrafoAmigos 
{
    int user1;
    int user2;
} _getNosGrafoAmigos;

// typeDescription: n/a
typedef struct _getNosGrafoAmigosResponse 
{
    unsigned int getNosGrafoAmigosResultCount;
    __field_ecount_opt(getNosGrafoAmigosResultCount)struct NoBD** getNosGrafoAmigosResult; // optional
} _getNosGrafoAmigosResponse;

// typeDescription: n/a
typedef struct _getNosGrafo 
{
    int userid;
} _getNosGrafo;

// typeDescription: n/a
typedef struct _getNosGrafoResponse 
{
    unsigned int getNosGrafoResultCount;
    __field_ecount_opt(getNosGrafoResultCount)struct NoBD** getNosGrafoResult; // optional
} _getNosGrafoResponse;

////////////////////////////////////////////////
// Global web service descriptions.
////////////////////////////////////////////////

typedef struct _tempuri_org_xsd
{
    struct // globalElements
    {
        // xml element: Add ("http://tempuri.org/")
        // c type: _Add
        // elementDescription: tempuri_org_xsd.globalElements.Add
        WS_ELEMENT_DESCRIPTION Add;
        
        // xml element: AddResponse ("http://tempuri.org/")
        // c type: _AddResponse
        // elementDescription: tempuri_org_xsd.globalElements.AddResponse
        WS_ELEMENT_DESCRIPTION AddResponse;
        
        // xml element: GetAllXY ("http://tempuri.org/")
        // c type: _GetAllXY
        // elementDescription: tempuri_org_xsd.globalElements.GetAllXY
        WS_ELEMENT_DESCRIPTION GetAllXY;
        
        // xml element: GetAllXYResponse ("http://tempuri.org/")
        // c type: _GetAllXYResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAllXYResponse
        WS_ELEMENT_DESCRIPTION GetAllXYResponse;
        
        // xml element: GetAllArcoBD ("http://tempuri.org/")
        // c type: _GetAllArcoBD
        // elementDescription: tempuri_org_xsd.globalElements.GetAllArcoBD
        WS_ELEMENT_DESCRIPTION GetAllArcoBD;
        
        // xml element: GetAllArcoBDResponse ("http://tempuri.org/")
        // c type: _GetAllArcoBDResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetAllArcoBDResponse
        WS_ELEMENT_DESCRIPTION GetAllArcoBDResponse;
        
        // xml element: GetUtilizadorByID ("http://tempuri.org/")
        // c type: _GetUtilizadorByID
        // elementDescription: tempuri_org_xsd.globalElements.GetUtilizadorByID
        WS_ELEMENT_DESCRIPTION GetUtilizadorByID;
        
        // xml element: GetUtilizadorByIDResponse ("http://tempuri.org/")
        // c type: _GetUtilizadorByIDResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetUtilizadorByIDResponse
        WS_ELEMENT_DESCRIPTION GetUtilizadorByIDResponse;
        
        // xml element: GetTagsByUserID ("http://tempuri.org/")
        // c type: _GetTagsByUserID
        // elementDescription: tempuri_org_xsd.globalElements.GetTagsByUserID
        WS_ELEMENT_DESCRIPTION GetTagsByUserID;
        
        // xml element: GetTagsByUserIDResponse ("http://tempuri.org/")
        // c type: _GetTagsByUserIDResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetTagsByUserIDResponse
        WS_ELEMENT_DESCRIPTION GetTagsByUserIDResponse;
        
        // xml element: GetHumorByUserID ("http://tempuri.org/")
        // c type: _GetHumorByUserID
        // elementDescription: tempuri_org_xsd.globalElements.GetHumorByUserID
        WS_ELEMENT_DESCRIPTION GetHumorByUserID;
        
        // xml element: GetHumorByUserIDResponse ("http://tempuri.org/")
        // c type: _GetHumorByUserIDResponse
        // elementDescription: tempuri_org_xsd.globalElements.GetHumorByUserIDResponse
        WS_ELEMENT_DESCRIPTION GetHumorByUserIDResponse;
        
        // xml element: getMenorCaminho ("http://tempuri.org/")
        // c type: _getMenorCaminho
        // elementDescription: tempuri_org_xsd.globalElements.getMenorCaminho
        WS_ELEMENT_DESCRIPTION getMenorCaminho;
        
        // xml element: getMenorCaminhoResponse ("http://tempuri.org/")
        // c type: _getMenorCaminhoResponse
        // elementDescription: tempuri_org_xsd.globalElements.getMenorCaminhoResponse
        WS_ELEMENT_DESCRIPTION getMenorCaminhoResponse;
        
        // xml element: getCaminhoForte ("http://tempuri.org/")
        // c type: _getCaminhoForte
        // elementDescription: tempuri_org_xsd.globalElements.getCaminhoForte
        WS_ELEMENT_DESCRIPTION getCaminhoForte;
        
        // xml element: getCaminhoForteResponse ("http://tempuri.org/")
        // c type: _getCaminhoForteResponse
        // elementDescription: tempuri_org_xsd.globalElements.getCaminhoForteResponse
        WS_ELEMENT_DESCRIPTION getCaminhoForteResponse;
        
        // xml element: DoWork ("http://tempuri.org/")
        // c type: _DoWork
        // elementDescription: tempuri_org_xsd.globalElements.DoWork
        WS_ELEMENT_DESCRIPTION DoWork;
        
        // xml element: DoWorkResponse ("http://tempuri.org/")
        // c type: _DoWorkResponse
        // elementDescription: tempuri_org_xsd.globalElements.DoWorkResponse
        WS_ELEMENT_DESCRIPTION DoWorkResponse;
        
        // xml element: validateLogin ("http://tempuri.org/")
        // c type: _validateLogin
        // elementDescription: tempuri_org_xsd.globalElements.validateLogin
        WS_ELEMENT_DESCRIPTION validateLogin;
        
        // xml element: validateLoginResponse ("http://tempuri.org/")
        // c type: _validateLoginResponse
        // elementDescription: tempuri_org_xsd.globalElements.validateLoginResponse
        WS_ELEMENT_DESCRIPTION validateLoginResponse;
        
        // xml element: xTagsEmComum ("http://tempuri.org/")
        // c type: _xTagsEmComum
        // elementDescription: tempuri_org_xsd.globalElements.xTagsEmComum
        WS_ELEMENT_DESCRIPTION xTagsEmComum;
        
        // xml element: xTagsEmComumResponse ("http://tempuri.org/")
        // c type: _xTagsEmComumResponse
        // elementDescription: tempuri_org_xsd.globalElements.xTagsEmComumResponse
        WS_ELEMENT_DESCRIPTION xTagsEmComumResponse;
        
        // xml element: tamanhoRedeUtilizador ("http://tempuri.org/")
        // c type: _tamanhoRedeUtilizador
        // elementDescription: tempuri_org_xsd.globalElements.tamanhoRedeUtilizador
        WS_ELEMENT_DESCRIPTION tamanhoRedeUtilizador;
        
        // xml element: tamanhoRedeUtilizadorResponse ("http://tempuri.org/")
        // c type: _tamanhoRedeUtilizadorResponse
        // elementDescription: tempuri_org_xsd.globalElements.tamanhoRedeUtilizadorResponse
        WS_ELEMENT_DESCRIPTION tamanhoRedeUtilizadorResponse;
        
        // xml element: sugereAmigos ("http://tempuri.org/")
        // c type: _sugereAmigos
        // elementDescription: tempuri_org_xsd.globalElements.sugereAmigos
        WS_ELEMENT_DESCRIPTION sugereAmigos;
        
        // xml element: sugereAmigosResponse ("http://tempuri.org/")
        // c type: _sugereAmigosResponse
        // elementDescription: tempuri_org_xsd.globalElements.sugereAmigosResponse
        WS_ELEMENT_DESCRIPTION sugereAmigosResponse;
        
        // xml element: grafoAmigosComuns ("http://tempuri.org/")
        // c type: _grafoAmigosComuns
        // elementDescription: tempuri_org_xsd.globalElements.grafoAmigosComuns
        WS_ELEMENT_DESCRIPTION grafoAmigosComuns;
        
        // xml element: grafoAmigosComunsResponse ("http://tempuri.org/")
        // c type: _grafoAmigosComunsResponse
        // elementDescription: tempuri_org_xsd.globalElements.grafoAmigosComunsResponse
        WS_ELEMENT_DESCRIPTION grafoAmigosComunsResponse;
        
        // xml element: getLigacao ("http://tempuri.org/")
        // c type: _getLigacao
        // elementDescription: tempuri_org_xsd.globalElements.getLigacao
        WS_ELEMENT_DESCRIPTION getLigacao;
        
        // xml element: getLigacaoResponse ("http://tempuri.org/")
        // c type: _getLigacaoResponse
        // elementDescription: tempuri_org_xsd.globalElements.getLigacaoResponse
        WS_ELEMENT_DESCRIPTION getLigacaoResponse;
        
        // xml element: getAmigosNivel3 ("http://tempuri.org/")
        // c type: _getAmigosNivel3
        // elementDescription: tempuri_org_xsd.globalElements.getAmigosNivel3
        WS_ELEMENT_DESCRIPTION getAmigosNivel3;
        
        // xml element: getAmigosNivel3Response ("http://tempuri.org/")
        // c type: _getAmigosNivel3Response
        // elementDescription: tempuri_org_xsd.globalElements.getAmigosNivel3Response
        WS_ELEMENT_DESCRIPTION getAmigosNivel3Response;
        
        // xml element: getMavenOfTag ("http://tempuri.org/")
        // c type: _getMavenOfTag
        // elementDescription: tempuri_org_xsd.globalElements.getMavenOfTag
        WS_ELEMENT_DESCRIPTION getMavenOfTag;
        
        // xml element: getMavenOfTagResponse ("http://tempuri.org/")
        // c type: _getMavenOfTagResponse
        // elementDescription: tempuri_org_xsd.globalElements.getMavenOfTagResponse
        WS_ELEMENT_DESCRIPTION getMavenOfTagResponse;
        
        // xml element: getSeparacao ("http://tempuri.org/")
        // c type: _getSeparacao
        // elementDescription: tempuri_org_xsd.globalElements.getSeparacao
        WS_ELEMENT_DESCRIPTION getSeparacao;
        
        // xml element: getSeparacaoResponse ("http://tempuri.org/")
        // c type: _getSeparacaoResponse
        // elementDescription: tempuri_org_xsd.globalElements.getSeparacaoResponse
        WS_ELEMENT_DESCRIPTION getSeparacaoResponse;
        
        // xml element: getGrafoNivel3 ("http://tempuri.org/")
        // c type: _getGrafoNivel3
        // elementDescription: tempuri_org_xsd.globalElements.getGrafoNivel3
        WS_ELEMENT_DESCRIPTION getGrafoNivel3;
        
        // xml element: getGrafoNivel3Response ("http://tempuri.org/")
        // c type: _getGrafoNivel3Response
        // elementDescription: tempuri_org_xsd.globalElements.getGrafoNivel3Response
        WS_ELEMENT_DESCRIPTION getGrafoNivel3Response;
        
        // xml element: getNosGrafoAmigos ("http://tempuri.org/")
        // c type: _getNosGrafoAmigos
        // elementDescription: tempuri_org_xsd.globalElements.getNosGrafoAmigos
        WS_ELEMENT_DESCRIPTION getNosGrafoAmigos;
        
        // xml element: getNosGrafoAmigosResponse ("http://tempuri.org/")
        // c type: _getNosGrafoAmigosResponse
        // elementDescription: tempuri_org_xsd.globalElements.getNosGrafoAmigosResponse
        WS_ELEMENT_DESCRIPTION getNosGrafoAmigosResponse;
        
        // xml element: getNosGrafo ("http://tempuri.org/")
        // c type: _getNosGrafo
        // elementDescription: tempuri_org_xsd.globalElements.getNosGrafo
        WS_ELEMENT_DESCRIPTION getNosGrafo;
        
        // xml element: getNosGrafoResponse ("http://tempuri.org/")
        // c type: _getNosGrafoResponse
        // elementDescription: tempuri_org_xsd.globalElements.getNosGrafoResponse
        WS_ELEMENT_DESCRIPTION getNosGrafoResponse;
        
    } globalElements;
    struct // externallyReferencedTypes
    {
        WS_STRUCT_DESCRIPTION Add;
        WS_STRUCT_DESCRIPTION AddResponse;
        WS_STRUCT_DESCRIPTION GetAllXY;
        WS_STRUCT_DESCRIPTION GetAllXYResponse;
        WS_STRUCT_DESCRIPTION GetAllArcoBD;
        WS_STRUCT_DESCRIPTION GetAllArcoBDResponse;
        WS_STRUCT_DESCRIPTION GetUtilizadorByID;
        WS_STRUCT_DESCRIPTION GetUtilizadorByIDResponse;
        WS_STRUCT_DESCRIPTION GetTagsByUserID;
        WS_STRUCT_DESCRIPTION GetTagsByUserIDResponse;
        WS_STRUCT_DESCRIPTION GetHumorByUserID;
        WS_STRUCT_DESCRIPTION GetHumorByUserIDResponse;
        WS_STRUCT_DESCRIPTION getMenorCaminho;
        WS_STRUCT_DESCRIPTION getMenorCaminhoResponse;
        WS_STRUCT_DESCRIPTION getCaminhoForte;
        WS_STRUCT_DESCRIPTION getCaminhoForteResponse;
        WS_STRUCT_DESCRIPTION DoWork;
        WS_STRUCT_DESCRIPTION DoWorkResponse;
        WS_STRUCT_DESCRIPTION validateLogin;
        WS_STRUCT_DESCRIPTION validateLoginResponse;
        WS_STRUCT_DESCRIPTION xTagsEmComum;
        WS_STRUCT_DESCRIPTION xTagsEmComumResponse;
        WS_STRUCT_DESCRIPTION tamanhoRedeUtilizador;
        WS_STRUCT_DESCRIPTION tamanhoRedeUtilizadorResponse;
        WS_STRUCT_DESCRIPTION sugereAmigos;
        WS_STRUCT_DESCRIPTION sugereAmigosResponse;
        WS_STRUCT_DESCRIPTION grafoAmigosComuns;
        WS_STRUCT_DESCRIPTION grafoAmigosComunsResponse;
        WS_STRUCT_DESCRIPTION getLigacao;
        WS_STRUCT_DESCRIPTION getLigacaoResponse;
        WS_STRUCT_DESCRIPTION getAmigosNivel3;
        WS_STRUCT_DESCRIPTION getAmigosNivel3Response;
        WS_STRUCT_DESCRIPTION getMavenOfTag;
        WS_STRUCT_DESCRIPTION getMavenOfTagResponse;
        WS_STRUCT_DESCRIPTION getSeparacao;
        WS_STRUCT_DESCRIPTION getSeparacaoResponse;
        WS_STRUCT_DESCRIPTION getGrafoNivel3;
        WS_STRUCT_DESCRIPTION getGrafoNivel3Response;
        WS_STRUCT_DESCRIPTION getNosGrafoAmigos;
        WS_STRUCT_DESCRIPTION getNosGrafoAmigosResponse;
        WS_STRUCT_DESCRIPTION getNosGrafo;
        WS_STRUCT_DESCRIPTION getNosGrafoResponse;
    } externallyReferencedTypes;
} _tempuri_org_xsd;

extern const _tempuri_org_xsd tempuri_org_xsd;

#ifdef __cplusplus
}
#endif

