
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schema.xsd.h"
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _Add
        {
            WS_FIELD_DESCRIPTION x;
            WS_FIELD_DESCRIPTION y;
            WS_FIELD_DESCRIPTION* _AddFields [2]; 
        } _Adddescs; // end of _Add
        struct // _AddResponse
        {
            WS_FIELD_DESCRIPTION AddResult;
            WS_FIELD_DESCRIPTION* _AddResponseFields [1]; 
        } _AddResponsedescs; // end of _AddResponse
        struct // _GetAllXYResponse
        {
            WS_FIELD_DESCRIPTION GetAllXYResult;
            WS_FIELD_DESCRIPTION* _GetAllXYResponseFields [1]; 
        } _GetAllXYResponsedescs; // end of _GetAllXYResponse
        struct // _GetAllArcoBDResponse
        {
            WS_FIELD_DESCRIPTION GetAllArcoBDResult;
            WS_FIELD_DESCRIPTION* _GetAllArcoBDResponseFields [1]; 
        } _GetAllArcoBDResponsedescs; // end of _GetAllArcoBDResponse
        struct // _GetUtilizadorByID
        {
            WS_FIELD_DESCRIPTION uid;
            WS_FIELD_DESCRIPTION* _GetUtilizadorByIDFields [1]; 
        } _GetUtilizadorByIDdescs; // end of _GetUtilizadorByID
        struct // _GetUtilizadorByIDResponse
        {
            WS_FIELD_DESCRIPTION GetUtilizadorByIDResult;
            WS_FIELD_DESCRIPTION* _GetUtilizadorByIDResponseFields [1]; 
        } _GetUtilizadorByIDResponsedescs; // end of _GetUtilizadorByIDResponse
        struct // _GetTagsByUserID
        {
            WS_FIELD_DESCRIPTION uid;
            WS_FIELD_DESCRIPTION* _GetTagsByUserIDFields [1]; 
        } _GetTagsByUserIDdescs; // end of _GetTagsByUserID
        struct // _GetTagsByUserIDResponse
        {
            WS_FIELD_DESCRIPTION GetTagsByUserIDResult;
            WS_FIELD_DESCRIPTION* _GetTagsByUserIDResponseFields [1]; 
        } _GetTagsByUserIDResponsedescs; // end of _GetTagsByUserIDResponse
        struct // _GetHumorByUserID
        {
            WS_FIELD_DESCRIPTION uid;
            WS_FIELD_DESCRIPTION* _GetHumorByUserIDFields [1]; 
        } _GetHumorByUserIDdescs; // end of _GetHumorByUserID
        struct // _GetHumorByUserIDResponse
        {
            WS_FIELD_DESCRIPTION GetHumorByUserIDResult;
            WS_FIELD_DESCRIPTION* _GetHumorByUserIDResponseFields [1]; 
        } _GetHumorByUserIDResponsedescs; // end of _GetHumorByUserIDResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _AddTypeName;  // Add
            WS_XML_STRING _AddTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _AddxLocalName;  // x
            WS_XML_STRING _AddyLocalName;  // y
            WS_XML_STRING _AddResponseTypeName;  // AddResponse
            WS_XML_STRING _AddResponseAddResultLocalName;  // AddResult
            WS_XML_STRING _GetAllXYTypeName;  // GetAllXY
            WS_XML_STRING _GetAllXYResponseTypeName;  // GetAllXYResponse
            WS_XML_STRING _GetAllXYResponseGetAllXYResultLocalName;  // NoBD
            WS_XML_STRING _GetAllXYResponseGetAllXYResultNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING _GetAllXYResponseGetAllXYResultWrapperName;  // GetAllXYResult
            WS_XML_STRING _GetAllArcoBDTypeName;  // GetAllArcoBD
            WS_XML_STRING _GetAllArcoBDResponseTypeName;  // GetAllArcoBDResponse
            WS_XML_STRING _GetAllArcoBDResponseGetAllArcoBDResultLocalName;  // ArcoBD
            WS_XML_STRING _GetAllArcoBDResponseGetAllArcoBDResultWrapperName;  // GetAllArcoBDResult
            WS_XML_STRING _GetUtilizadorByIDTypeName;  // GetUtilizadorByID
            WS_XML_STRING _GetUtilizadorByIDuidLocalName;  // uid
            WS_XML_STRING _GetUtilizadorByIDResponseTypeName;  // GetUtilizadorByIDResponse
            WS_XML_STRING _GetUtilizadorByIDResponseGetUtilizadorByIDResultLocalName;  // GetUtilizadorByIDResult
            WS_XML_STRING _GetTagsByUserIDTypeName;  // GetTagsByUserID
            WS_XML_STRING _GetTagsByUserIDResponseTypeName;  // GetTagsByUserIDResponse
            WS_XML_STRING _GetTagsByUserIDResponseGetTagsByUserIDResultLocalName;  // anyType
            WS_XML_STRING _GetTagsByUserIDResponseGetTagsByUserIDResultNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            WS_XML_STRING _GetTagsByUserIDResponseGetTagsByUserIDResultWrapperName;  // GetTagsByUserIDResult
            WS_XML_STRING _GetHumorByUserIDTypeName;  // GetHumorByUserID
            WS_XML_STRING _GetHumorByUserIDResponseTypeName;  // GetHumorByUserIDResponse
            WS_XML_STRING _GetHumorByUserIDResponseGetHumorByUserIDResultLocalName;  // GetHumorByUserIDResult
            WS_XML_STRING _DoWorkTypeName;  // DoWork
            WS_XML_STRING _DoWorkResponseTypeName;  // DoWorkResponse
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _Add
            { // field description for x
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddxLocalName, // x
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, x),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for x
            { // field description for y
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddyLocalName, // y
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, y),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for y
            {    // fields description for _Add
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.x,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.y,
            },
        },    // _Add
        {   // _AddResponse
            { // field description for AddResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseAddResultLocalName, // AddResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddResponse, AddResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for AddResult
            {    // fields description for _AddResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs.AddResult,
            },
        },    // _AddResponse
        {   // _GetAllXYResponse
            { // field description for GetAllXYResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultWrapperName, // GetAllXYResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.NoBD,
            WsOffsetOf(_GetAllXYResponse, GetAllXYResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_GetAllXYResponse, GetAllXYResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultLocalName, // NoBD
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for GetAllXYResult
            {    // fields description for _GetAllXYResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs.GetAllXYResult,
            },
        },    // _GetAllXYResponse
        {   // _GetAllArcoBDResponse
            { // field description for GetAllArcoBDResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseGetAllArcoBDResultWrapperName, // GetAllArcoBDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArcoBD,
            WsOffsetOf(_GetAllArcoBDResponse, GetAllArcoBDResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_GetAllArcoBDResponse, GetAllArcoBDResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseGetAllArcoBDResultLocalName, // ArcoBD
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for GetAllArcoBDResult
            {    // fields description for _GetAllArcoBDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllArcoBDResponsedescs.GetAllArcoBDResult,
            },
        },    // _GetAllArcoBDResponse
        {   // _GetUtilizadorByID
            { // field description for uid
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDuidLocalName, // uid
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_GetUtilizadorByID, uid),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for uid
            {    // fields description for _GetUtilizadorByID
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDdescs.uid,
            },
        },    // _GetUtilizadorByID
        {   // _GetUtilizadorByIDResponse
            { // field description for GetUtilizadorByIDResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDResponseGetUtilizadorByIDResultLocalName, // GetUtilizadorByIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Utilizador,
            WsOffsetOf(_GetUtilizadorByIDResponse, GetUtilizadorByIDResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for GetUtilizadorByIDResult
            {    // fields description for _GetUtilizadorByIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDResponsedescs.GetUtilizadorByIDResult,
            },
        },    // _GetUtilizadorByIDResponse
        {   // _GetTagsByUserID
            { // field description for uid
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDuidLocalName, // uid
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_GetTagsByUserID, uid),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for uid
            {    // fields description for _GetTagsByUserID
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDdescs.uid,
            },
        },    // _GetTagsByUserID
        {   // _GetTagsByUserIDResponse
            { // field description for GetTagsByUserIDResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseGetTagsByUserIDResultWrapperName, // GetTagsByUserIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_XML_BUFFER_TYPE,
            0,
            WsOffsetOf(_GetTagsByUserIDResponse, GetTagsByUserIDResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_GetTagsByUserIDResponse, GetTagsByUserIDResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseGetTagsByUserIDResultLocalName, // anyType
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseGetTagsByUserIDResultNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            0,
            },    // end of field description for GetTagsByUserIDResult
            {    // fields description for _GetTagsByUserIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDResponsedescs.GetTagsByUserIDResult,
            },
        },    // _GetTagsByUserIDResponse
        {   // _GetHumorByUserID
            { // field description for uid
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDuidLocalName, // uid
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_GetHumorByUserID, uid),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for uid
            {    // fields description for _GetHumorByUserID
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDdescs.uid,
            },
        },    // _GetHumorByUserID
        {   // _GetHumorByUserIDResponse
            { // field description for GetHumorByUserIDResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDResponseGetHumorByUserIDResultLocalName, // GetHumorByUserIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_GetHumorByUserIDResponse, GetHumorByUserIDResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for GetHumorByUserIDResult
            {    // fields description for _GetHumorByUserIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDResponsedescs.GetHumorByUserIDResult,
            },
        },    // _GetHumorByUserIDResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Add",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("x",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("y",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("AddResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("AddResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXY",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXYResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("NoBD",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXYResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllArcoBD",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllArcoBDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("ArcoBD",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllArcoBDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("GetUtilizadorByID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("uid",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("GetUtilizadorByIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("GetUtilizadorByIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("GetTagsByUserID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("GetTagsByUserIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("anyType",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/Arrays",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("GetTagsByUserIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("GetHumorByUserID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("GetHumorByUserIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("GetHumorByUserIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("DoWork",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 27),
            WS_XML_STRING_DICTIONARY_VALUE("DoWorkResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 28),
        },  // end of xmlStrings
        
        {   // tempuri_org_xsddictionary
        // c7780069-c9f0-4bf8-891e-8ebd7b8ef432 
        { 0xc7780069, 0xc9f0, 0x4bf8, { 0x89, 0x1e, 0x8e,0xbd, 0x7b, 0x8e, 0xf4, 0x32 } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        29,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.Add,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.AddResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYTypeName, // GetAllXY
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllXY,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseTypeName, // GetAllXYResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllXYResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDTypeName, // GetAllArcoBD
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllArcoBD,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseTypeName, // GetAllArcoBDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllArcoBDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDTypeName, // GetUtilizadorByID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetUtilizadorByID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDResponseTypeName, // GetUtilizadorByIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetUtilizadorByIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDTypeName, // GetTagsByUserID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetTagsByUserID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseTypeName, // GetTagsByUserIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetTagsByUserIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDTypeName, // GetHumorByUserID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetHumorByUserID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDResponseTypeName, // GetHumorByUserIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetHumorByUserIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWork,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWorkResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_Add),
        __alignof(_Add),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _Add
        {
        sizeof(_AddResponse),
        __alignof(_AddResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _AddResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYTypeName, // GetAllXY
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllXY
        {
        sizeof(_GetAllXYResponse),
        __alignof(_GetAllXYResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs._GetAllXYResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs._GetAllXYResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseTypeName, // GetAllXYResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllXYResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDTypeName, // GetAllArcoBD
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllArcoBD
        {
        sizeof(_GetAllArcoBDResponse),
        __alignof(_GetAllArcoBDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllArcoBDResponsedescs._GetAllArcoBDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetAllArcoBDResponsedescs._GetAllArcoBDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseTypeName, // GetAllArcoBDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllArcoBDResponse
        {
        sizeof(_GetUtilizadorByID),
        __alignof(_GetUtilizadorByID),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDdescs._GetUtilizadorByIDFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDdescs._GetUtilizadorByIDFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDTypeName, // GetUtilizadorByID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetUtilizadorByID
        {
        sizeof(_GetUtilizadorByIDResponse),
        __alignof(_GetUtilizadorByIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDResponsedescs._GetUtilizadorByIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDResponsedescs._GetUtilizadorByIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDResponseTypeName, // GetUtilizadorByIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetUtilizadorByIDResponse
        {
        sizeof(_GetTagsByUserID),
        __alignof(_GetTagsByUserID),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDdescs._GetTagsByUserIDFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDdescs._GetTagsByUserIDFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDTypeName, // GetTagsByUserID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetTagsByUserID
        {
        sizeof(_GetTagsByUserIDResponse),
        __alignof(_GetTagsByUserIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDResponsedescs._GetTagsByUserIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDResponsedescs._GetTagsByUserIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseTypeName, // GetTagsByUserIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetTagsByUserIDResponse
        {
        sizeof(_GetHumorByUserID),
        __alignof(_GetHumorByUserID),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDdescs._GetHumorByUserIDFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDdescs._GetHumorByUserIDFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDTypeName, // GetHumorByUserID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetHumorByUserID
        {
        sizeof(_GetHumorByUserIDResponse),
        __alignof(_GetHumorByUserIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDResponsedescs._GetHumorByUserIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDResponsedescs._GetHumorByUserIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDResponseTypeName, // GetHumorByUserIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetHumorByUserIDResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWork
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWorkResponse
    }, // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
