
// File generated by Wsutil Compiler version 1.0092 
#include <WebServices.h>
#include "schema.xsd.h"
#include "schemas.microsoft.com.2003.10.Serialization.Arrays.xsd.h"
#include "tempuri.org.xsd.h"

typedef struct _tempuri_org_xsdLocalDefinitions 
{
    struct  // global elements
    {
    char unused;
        struct // _Add
        {
            WS_FIELD_DESCRIPTION x;
            WS_FIELD_DESCRIPTION y;
            WS_FIELD_DESCRIPTION* _AddFields [2]; 
        } _Adddescs; // end of _Add
        struct // _AddResponse
        {
            WS_FIELD_DESCRIPTION AddResult;
            WS_FIELD_DESCRIPTION* _AddResponseFields [1]; 
        } _AddResponsedescs; // end of _AddResponse
        struct // _GetAllXYResponse
        {
            WS_FIELD_DESCRIPTION GetAllXYResult;
            WS_FIELD_DESCRIPTION* _GetAllXYResponseFields [1]; 
        } _GetAllXYResponsedescs; // end of _GetAllXYResponse
        struct // _GetAllArcoBDResponse
        {
            WS_FIELD_DESCRIPTION GetAllArcoBDResult;
            WS_FIELD_DESCRIPTION* _GetAllArcoBDResponseFields [1]; 
        } _GetAllArcoBDResponsedescs; // end of _GetAllArcoBDResponse
        struct // _GetUtilizadorByID
        {
            WS_FIELD_DESCRIPTION uid;
            WS_FIELD_DESCRIPTION* _GetUtilizadorByIDFields [1]; 
        } _GetUtilizadorByIDdescs; // end of _GetUtilizadorByID
        struct // _GetUtilizadorByIDResponse
        {
            WS_FIELD_DESCRIPTION GetUtilizadorByIDResult;
            WS_FIELD_DESCRIPTION* _GetUtilizadorByIDResponseFields [1]; 
        } _GetUtilizadorByIDResponsedescs; // end of _GetUtilizadorByIDResponse
        struct // _GetTagsByUserID
        {
            WS_FIELD_DESCRIPTION uid;
            WS_FIELD_DESCRIPTION* _GetTagsByUserIDFields [1]; 
        } _GetTagsByUserIDdescs; // end of _GetTagsByUserID
        struct // _GetTagsByUserIDResponse
        {
            WS_FIELD_DESCRIPTION GetTagsByUserIDResult;
            WS_FIELD_DESCRIPTION* _GetTagsByUserIDResponseFields [1]; 
        } _GetTagsByUserIDResponsedescs; // end of _GetTagsByUserIDResponse
        struct // _GetHumorByUserID
        {
            WS_FIELD_DESCRIPTION uid;
            WS_FIELD_DESCRIPTION* _GetHumorByUserIDFields [1]; 
        } _GetHumorByUserIDdescs; // end of _GetHumorByUserID
        struct // _GetHumorByUserIDResponse
        {
            WS_FIELD_DESCRIPTION GetHumorByUserIDResult;
            WS_FIELD_DESCRIPTION* _GetHumorByUserIDResponseFields [1]; 
        } _GetHumorByUserIDResponsedescs; // end of _GetHumorByUserIDResponse
        struct // _getMenorCaminho
        {
            WS_FIELD_DESCRIPTION no1;
            WS_FIELD_DESCRIPTION no2;
            WS_FIELD_DESCRIPTION* _getMenorCaminhoFields [2]; 
        } _getMenorCaminhodescs; // end of _getMenorCaminho
        struct // _getMenorCaminhoResponse
        {
            WS_FIELD_DESCRIPTION getMenorCaminhoResult;
            WS_FIELD_DESCRIPTION* _getMenorCaminhoResponseFields [1]; 
        } _getMenorCaminhoResponsedescs; // end of _getMenorCaminhoResponse
        struct // _getCaminhoForte
        {
            WS_FIELD_DESCRIPTION no1;
            WS_FIELD_DESCRIPTION no2;
            WS_FIELD_DESCRIPTION* _getCaminhoForteFields [2]; 
        } _getCaminhoFortedescs; // end of _getCaminhoForte
        struct // _getCaminhoForteResponse
        {
            WS_FIELD_DESCRIPTION getCaminhoForteResult;
            WS_FIELD_DESCRIPTION* _getCaminhoForteResponseFields [1]; 
        } _getCaminhoForteResponsedescs; // end of _getCaminhoForteResponse
        struct // _validateLogin
        {
            WS_FIELD_DESCRIPTION userName;
            WS_FIELD_DESCRIPTION password;
            WS_FIELD_DESCRIPTION* _validateLoginFields [2]; 
        } _validateLogindescs; // end of _validateLogin
        struct // _validateLoginResponse
        {
            WS_FIELD_DESCRIPTION validateLoginResult;
            WS_FIELD_DESCRIPTION* _validateLoginResponseFields [1]; 
        } _validateLoginResponsedescs; // end of _validateLoginResponse
        struct // _xTagsEmComum
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION n;
            WS_FIELD_DESCRIPTION* _xTagsEmComumFields [2]; 
        } _xTagsEmComumdescs; // end of _xTagsEmComum
        struct // _xTagsEmComumResponse
        {
            WS_FIELD_DESCRIPTION xTagsEmComumResult;
            WS_FIELD_DESCRIPTION* _xTagsEmComumResponseFields [1]; 
        } _xTagsEmComumResponsedescs; // end of _xTagsEmComumResponse
        struct // _tamanhoRedeUtilizador
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION* _tamanhoRedeUtilizadorFields [1]; 
        } _tamanhoRedeUtilizadordescs; // end of _tamanhoRedeUtilizador
        struct // _tamanhoRedeUtilizadorResponse
        {
            WS_FIELD_DESCRIPTION tamanhoRedeUtilizadorResult;
            WS_FIELD_DESCRIPTION* _tamanhoRedeUtilizadorResponseFields [1]; 
        } _tamanhoRedeUtilizadorResponsedescs; // end of _tamanhoRedeUtilizadorResponse
        struct // _sugereAmigos
        {
            WS_FIELD_DESCRIPTION id;
            WS_FIELD_DESCRIPTION* _sugereAmigosFields [1]; 
        } _sugereAmigosdescs; // end of _sugereAmigos
        struct // _sugereAmigosResponse
        {
            WS_FIELD_DESCRIPTION sugereAmigosResult;
            WS_FIELD_DESCRIPTION* _sugereAmigosResponseFields [1]; 
        } _sugereAmigosResponsedescs; // end of _sugereAmigosResponse
    } globalElements;  // end of global elements
    struct // XML dictionary
    {
        struct // XML string list
        {
            WS_XML_STRING _AddTypeName;  // Add
            WS_XML_STRING _AddTypeNamespace;  // http://tempuri.org/
            WS_XML_STRING _AddxLocalName;  // x
            WS_XML_STRING _AddyLocalName;  // y
            WS_XML_STRING _AddResponseTypeName;  // AddResponse
            WS_XML_STRING _AddResponseAddResultLocalName;  // AddResult
            WS_XML_STRING _GetAllXYTypeName;  // GetAllXY
            WS_XML_STRING _GetAllXYResponseTypeName;  // GetAllXYResponse
            WS_XML_STRING _GetAllXYResponseGetAllXYResultLocalName;  // NoBD
            WS_XML_STRING _GetAllXYResponseGetAllXYResultNamespace;  // http://schemas.datacontract.org/2004/07/
            WS_XML_STRING _GetAllXYResponseGetAllXYResultWrapperName;  // GetAllXYResult
            WS_XML_STRING _GetAllArcoBDTypeName;  // GetAllArcoBD
            WS_XML_STRING _GetAllArcoBDResponseTypeName;  // GetAllArcoBDResponse
            WS_XML_STRING _GetAllArcoBDResponseGetAllArcoBDResultLocalName;  // ArcoBD
            WS_XML_STRING _GetAllArcoBDResponseGetAllArcoBDResultWrapperName;  // GetAllArcoBDResult
            WS_XML_STRING _GetUtilizadorByIDTypeName;  // GetUtilizadorByID
            WS_XML_STRING _GetUtilizadorByIDuidLocalName;  // uid
            WS_XML_STRING _GetUtilizadorByIDResponseTypeName;  // GetUtilizadorByIDResponse
            WS_XML_STRING _GetUtilizadorByIDResponseGetUtilizadorByIDResultLocalName;  // GetUtilizadorByIDResult
            WS_XML_STRING _GetTagsByUserIDTypeName;  // GetTagsByUserID
            WS_XML_STRING _GetTagsByUserIDResponseTypeName;  // GetTagsByUserIDResponse
            WS_XML_STRING _GetTagsByUserIDResponseGetTagsByUserIDResultLocalName;  // string
            WS_XML_STRING _GetTagsByUserIDResponseGetTagsByUserIDResultNamespace;  // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            WS_XML_STRING _GetTagsByUserIDResponseGetTagsByUserIDResultWrapperName;  // GetTagsByUserIDResult
            WS_XML_STRING _GetHumorByUserIDTypeName;  // GetHumorByUserID
            WS_XML_STRING _GetHumorByUserIDResponseTypeName;  // GetHumorByUserIDResponse
            WS_XML_STRING _GetHumorByUserIDResponseGetHumorByUserIDResultLocalName;  // GetHumorByUserIDResult
            WS_XML_STRING _getMenorCaminhoTypeName;  // getMenorCaminho
            WS_XML_STRING _getMenorCaminhono1LocalName;  // no1
            WS_XML_STRING _getMenorCaminhono2LocalName;  // no2
            WS_XML_STRING _getMenorCaminhoResponseTypeName;  // getMenorCaminhoResponse
            WS_XML_STRING _getMenorCaminhoResponsegetMenorCaminhoResultLocalName;  // getMenorCaminhoResult
            WS_XML_STRING _getCaminhoForteTypeName;  // getCaminhoForte
            WS_XML_STRING _getCaminhoForteResponseTypeName;  // getCaminhoForteResponse
            WS_XML_STRING _getCaminhoForteResponsegetCaminhoForteResultLocalName;  // getCaminhoForteResult
            WS_XML_STRING _DoWorkTypeName;  // DoWork
            WS_XML_STRING _DoWorkResponseTypeName;  // DoWorkResponse
            WS_XML_STRING _validateLoginTypeName;  // validateLogin
            WS_XML_STRING _validateLoginuserNameLocalName;  // userName
            WS_XML_STRING _validateLoginpasswordLocalName;  // password
            WS_XML_STRING _validateLoginResponseTypeName;  // validateLoginResponse
            WS_XML_STRING _validateLoginResponsevalidateLoginResultLocalName;  // validateLoginResult
            WS_XML_STRING _xTagsEmComumTypeName;  // xTagsEmComum
            WS_XML_STRING _xTagsEmComumidLocalName;  // id
            WS_XML_STRING _xTagsEmComumnLocalName;  // n
            WS_XML_STRING _xTagsEmComumResponseTypeName;  // xTagsEmComumResponse
            WS_XML_STRING _xTagsEmComumResponsexTagsEmComumResultLocalName;  // xTagsEmComumResult
            WS_XML_STRING _tamanhoRedeUtilizadorTypeName;  // tamanhoRedeUtilizador
            WS_XML_STRING _tamanhoRedeUtilizadorResponseTypeName;  // tamanhoRedeUtilizadorResponse
            WS_XML_STRING _tamanhoRedeUtilizadorResponsetamanhoRedeUtilizadorResultLocalName;  // tamanhoRedeUtilizadorResult
            WS_XML_STRING _sugereAmigosTypeName;  // sugereAmigos
            WS_XML_STRING _sugereAmigosResponseTypeName;  // sugereAmigosResponse
            WS_XML_STRING _sugereAmigosResponsesugereAmigosResultLocalName;  // sugereAmigosResult
        } xmlStrings; // end of XML string list
        WS_XML_DICTIONARY dict;  
    } dictionary;  // end of XML dictionary
} _tempuri_org_xsdLocalDefinitions;

const static _tempuri_org_xsdLocalDefinitions tempuri_org_xsdLocalDefinitions =
{
    {  // global elements
        0,
        {   // _Add
            { // field description for x
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddxLocalName, // x
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, x),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for x
            { // field description for y
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddyLocalName, // y
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_Add, y),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for y
            {    // fields description for _Add
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.x,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs.y,
            },
        },    // _Add
        {   // _AddResponse
            { // field description for AddResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseAddResultLocalName, // AddResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_AddResponse, AddResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for AddResult
            {    // fields description for _AddResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs.AddResult,
            },
        },    // _AddResponse
        {   // _GetAllXYResponse
            { // field description for GetAllXYResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultWrapperName, // GetAllXYResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.NoBD,
            WsOffsetOf(_GetAllXYResponse, GetAllXYResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_GetAllXYResponse, GetAllXYResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultLocalName, // NoBD
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for GetAllXYResult
            {    // fields description for _GetAllXYResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs.GetAllXYResult,
            },
        },    // _GetAllXYResponse
        {   // _GetAllArcoBDResponse
            { // field description for GetAllArcoBDResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseGetAllArcoBDResultWrapperName, // GetAllArcoBDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.ArcoBD,
            WsOffsetOf(_GetAllArcoBDResponse, GetAllArcoBDResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_GetAllArcoBDResponse, GetAllArcoBDResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseGetAllArcoBDResultLocalName, // ArcoBD
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseGetAllXYResultNamespace, // http://schemas.datacontract.org/2004/07/
            0,
            },    // end of field description for GetAllArcoBDResult
            {    // fields description for _GetAllArcoBDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllArcoBDResponsedescs.GetAllArcoBDResult,
            },
        },    // _GetAllArcoBDResponse
        {   // _GetUtilizadorByID
            { // field description for uid
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDuidLocalName, // uid
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_GetUtilizadorByID, uid),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for uid
            {    // fields description for _GetUtilizadorByID
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDdescs.uid,
            },
        },    // _GetUtilizadorByID
        {   // _GetUtilizadorByIDResponse
            { // field description for GetUtilizadorByIDResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDResponseGetUtilizadorByIDResultLocalName, // GetUtilizadorByIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&schema_xsd.globalTypes.Utilizador,
            WsOffsetOf(_GetUtilizadorByIDResponse, GetUtilizadorByIDResult),
            WS_FIELD_POINTER| WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for GetUtilizadorByIDResult
            {    // fields description for _GetUtilizadorByIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDResponsedescs.GetUtilizadorByIDResult,
            },
        },    // _GetUtilizadorByIDResponse
        {   // _GetTagsByUserID
            { // field description for uid
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDuidLocalName, // uid
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_GetTagsByUserID, uid),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for uid
            {    // fields description for _GetTagsByUserID
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDdescs.uid,
            },
        },    // _GetTagsByUserID
        {   // _GetTagsByUserIDResponse
            { // field description for GetTagsByUserIDResult
            WS_REPEATING_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseGetTagsByUserIDResultWrapperName, // GetTagsByUserIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_GetTagsByUserIDResponse, GetTagsByUserIDResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE| WS_FIELD_NILLABLE_ITEM,
            0,
            WsOffsetOf(_GetTagsByUserIDResponse, GetTagsByUserIDResultCount),
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseGetTagsByUserIDResultLocalName, // string
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseGetTagsByUserIDResultNamespace, // http://schemas.microsoft.com/2003/10/Serialization/Arrays
            0,
            },    // end of field description for GetTagsByUserIDResult
            {    // fields description for _GetTagsByUserIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDResponsedescs.GetTagsByUserIDResult,
            },
        },    // _GetTagsByUserIDResponse
        {   // _GetHumorByUserID
            { // field description for uid
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDuidLocalName, // uid
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_GetHumorByUserID, uid),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for uid
            {    // fields description for _GetHumorByUserID
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDdescs.uid,
            },
        },    // _GetHumorByUserID
        {   // _GetHumorByUserIDResponse
            { // field description for GetHumorByUserIDResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDResponseGetHumorByUserIDResultLocalName, // GetHumorByUserIDResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_GetHumorByUserIDResponse, GetHumorByUserIDResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for GetHumorByUserIDResult
            {    // fields description for _GetHumorByUserIDResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDResponsedescs.GetHumorByUserIDResult,
            },
        },    // _GetHumorByUserIDResponse
        {   // _getMenorCaminho
            { // field description for no1
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhono1LocalName, // no1
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getMenorCaminho, no1),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for no1
            { // field description for no2
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhono2LocalName, // no2
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getMenorCaminho, no2),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for no2
            {    // fields description for _getMenorCaminho
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getMenorCaminhodescs.no1,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getMenorCaminhodescs.no2,
            },
        },    // _getMenorCaminho
        {   // _getMenorCaminhoResponse
            { // field description for getMenorCaminhoResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhoResponsegetMenorCaminhoResultLocalName, // getMenorCaminhoResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getMenorCaminhoResponse, getMenorCaminhoResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for getMenorCaminhoResult
            {    // fields description for _getMenorCaminhoResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getMenorCaminhoResponsedescs.getMenorCaminhoResult,
            },
        },    // _getMenorCaminhoResponse
        {   // _getCaminhoForte
            { // field description for no1
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhono1LocalName, // no1
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getCaminhoForte, no1),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for no1
            { // field description for no2
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhono2LocalName, // no2
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_getCaminhoForte, no2),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for no2
            {    // fields description for _getCaminhoForte
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getCaminhoFortedescs.no1,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getCaminhoFortedescs.no2,
            },
        },    // _getCaminhoForte
        {   // _getCaminhoForteResponse
            { // field description for getCaminhoForteResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getCaminhoForteResponsegetCaminhoForteResultLocalName, // getCaminhoForteResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_getCaminhoForteResponse, getCaminhoForteResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for getCaminhoForteResult
            {    // fields description for _getCaminhoForteResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._getCaminhoForteResponsedescs.getCaminhoForteResult,
            },
        },    // _getCaminhoForteResponse
        {   // _validateLogin
            { // field description for userName
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._validateLoginuserNameLocalName, // userName
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_validateLogin, userName),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for userName
            { // field description for password
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._validateLoginpasswordLocalName, // password
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_validateLogin, password),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for password
            {    // fields description for _validateLogin
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._validateLogindescs.userName,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._validateLogindescs.password,
            },
        },    // _validateLogin
        {   // _validateLoginResponse
            { // field description for validateLoginResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._validateLoginResponsevalidateLoginResultLocalName, // validateLoginResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_validateLoginResponse, validateLoginResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for validateLoginResult
            {    // fields description for _validateLoginResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._validateLoginResponsedescs.validateLoginResult,
            },
        },    // _validateLoginResponse
        {   // _xTagsEmComum
            { // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_xTagsEmComum, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            { // field description for n
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumnLocalName, // n
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_xTagsEmComum, n),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for n
            {    // fields description for _xTagsEmComum
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._xTagsEmComumdescs.id,
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._xTagsEmComumdescs.n,
            },
        },    // _xTagsEmComum
        {   // _xTagsEmComumResponse
            { // field description for xTagsEmComumResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumResponsexTagsEmComumResultLocalName, // xTagsEmComumResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_xTagsEmComumResponse, xTagsEmComumResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for xTagsEmComumResult
            {    // fields description for _xTagsEmComumResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._xTagsEmComumResponsedescs.xTagsEmComumResult,
            },
        },    // _xTagsEmComumResponse
        {   // _tamanhoRedeUtilizador
            { // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_tamanhoRedeUtilizador, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {    // fields description for _tamanhoRedeUtilizador
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._tamanhoRedeUtilizadordescs.id,
            },
        },    // _tamanhoRedeUtilizador
        {   // _tamanhoRedeUtilizadorResponse
            { // field description for tamanhoRedeUtilizadorResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._tamanhoRedeUtilizadorResponsetamanhoRedeUtilizadorResultLocalName, // tamanhoRedeUtilizadorResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_tamanhoRedeUtilizadorResponse, tamanhoRedeUtilizadorResult),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for tamanhoRedeUtilizadorResult
            {    // fields description for _tamanhoRedeUtilizadorResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._tamanhoRedeUtilizadorResponsedescs.tamanhoRedeUtilizadorResult,
            },
        },    // _tamanhoRedeUtilizadorResponse
        {   // _sugereAmigos
            { // field description for id
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumidLocalName, // id
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_INT32_TYPE,
            0,
            WsOffsetOf(_sugereAmigos, id),
             WS_FIELD_OPTIONAL,
            0,
            0xffffffff
            },    // end of field description for id
            {    // fields description for _sugereAmigos
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._sugereAmigosdescs.id,
            },
        },    // _sugereAmigos
        {   // _sugereAmigosResponse
            { // field description for sugereAmigosResult
            WS_ELEMENT_FIELD_MAPPING,
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._sugereAmigosResponsesugereAmigosResultLocalName, // sugereAmigosResult
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_WSZ_TYPE,
            0,
            WsOffsetOf(_sugereAmigosResponse, sugereAmigosResult),
             WS_FIELD_OPTIONAL| WS_FIELD_NILLABLE,
            0,
            0xffffffff
            },    // end of field description for sugereAmigosResult
            {    // fields description for _sugereAmigosResponse
            (WS_FIELD_DESCRIPTION*)&tempuri_org_xsdLocalDefinitions.globalElements._sugereAmigosResponsedescs.sugereAmigosResult,
            },
        },    // _sugereAmigosResponse
    }, // end of global elements
    {    // dictionary 
        { // xmlStrings
            WS_XML_STRING_DICTIONARY_VALUE("Add",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 0),
            WS_XML_STRING_DICTIONARY_VALUE("http://tempuri.org/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 1),
            WS_XML_STRING_DICTIONARY_VALUE("x",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 2),
            WS_XML_STRING_DICTIONARY_VALUE("y",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 3),
            WS_XML_STRING_DICTIONARY_VALUE("AddResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 4),
            WS_XML_STRING_DICTIONARY_VALUE("AddResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 5),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXY",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 6),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXYResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 7),
            WS_XML_STRING_DICTIONARY_VALUE("NoBD",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 8),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.datacontract.org/2004/07/",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 9),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllXYResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 10),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllArcoBD",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 11),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllArcoBDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 12),
            WS_XML_STRING_DICTIONARY_VALUE("ArcoBD",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 13),
            WS_XML_STRING_DICTIONARY_VALUE("GetAllArcoBDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 14),
            WS_XML_STRING_DICTIONARY_VALUE("GetUtilizadorByID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 15),
            WS_XML_STRING_DICTIONARY_VALUE("uid",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 16),
            WS_XML_STRING_DICTIONARY_VALUE("GetUtilizadorByIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 17),
            WS_XML_STRING_DICTIONARY_VALUE("GetUtilizadorByIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 18),
            WS_XML_STRING_DICTIONARY_VALUE("GetTagsByUserID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 19),
            WS_XML_STRING_DICTIONARY_VALUE("GetTagsByUserIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 20),
            WS_XML_STRING_DICTIONARY_VALUE("string",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 21),
            WS_XML_STRING_DICTIONARY_VALUE("http://schemas.microsoft.com/2003/10/Serialization/Arrays",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 22),
            WS_XML_STRING_DICTIONARY_VALUE("GetTagsByUserIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 23),
            WS_XML_STRING_DICTIONARY_VALUE("GetHumorByUserID",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 24),
            WS_XML_STRING_DICTIONARY_VALUE("GetHumorByUserIDResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 25),
            WS_XML_STRING_DICTIONARY_VALUE("GetHumorByUserIDResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 26),
            WS_XML_STRING_DICTIONARY_VALUE("getMenorCaminho",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 27),
            WS_XML_STRING_DICTIONARY_VALUE("no1",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 28),
            WS_XML_STRING_DICTIONARY_VALUE("no2",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 29),
            WS_XML_STRING_DICTIONARY_VALUE("getMenorCaminhoResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 30),
            WS_XML_STRING_DICTIONARY_VALUE("getMenorCaminhoResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 31),
            WS_XML_STRING_DICTIONARY_VALUE("getCaminhoForte",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 32),
            WS_XML_STRING_DICTIONARY_VALUE("getCaminhoForteResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 33),
            WS_XML_STRING_DICTIONARY_VALUE("getCaminhoForteResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 34),
            WS_XML_STRING_DICTIONARY_VALUE("DoWork",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 35),
            WS_XML_STRING_DICTIONARY_VALUE("DoWorkResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 36),
            WS_XML_STRING_DICTIONARY_VALUE("validateLogin",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 37),
            WS_XML_STRING_DICTIONARY_VALUE("userName",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 38),
            WS_XML_STRING_DICTIONARY_VALUE("password",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 39),
            WS_XML_STRING_DICTIONARY_VALUE("validateLoginResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 40),
            WS_XML_STRING_DICTIONARY_VALUE("validateLoginResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 41),
            WS_XML_STRING_DICTIONARY_VALUE("xTagsEmComum",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 42),
            WS_XML_STRING_DICTIONARY_VALUE("id",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 43),
            WS_XML_STRING_DICTIONARY_VALUE("n",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 44),
            WS_XML_STRING_DICTIONARY_VALUE("xTagsEmComumResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 45),
            WS_XML_STRING_DICTIONARY_VALUE("xTagsEmComumResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 46),
            WS_XML_STRING_DICTIONARY_VALUE("tamanhoRedeUtilizador",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 47),
            WS_XML_STRING_DICTIONARY_VALUE("tamanhoRedeUtilizadorResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 48),
            WS_XML_STRING_DICTIONARY_VALUE("tamanhoRedeUtilizadorResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 49),
            WS_XML_STRING_DICTIONARY_VALUE("sugereAmigos",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 50),
            WS_XML_STRING_DICTIONARY_VALUE("sugereAmigosResponse",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 51),
            WS_XML_STRING_DICTIONARY_VALUE("sugereAmigosResult",&tempuri_org_xsdLocalDefinitions.dictionary.dict, 52),
        },  // end of xmlStrings
        
        {   // tempuri_org_xsddictionary
        // fa7beefe-5b81-4b04-9753-0d69b0ddaf5f 
        { 0xfa7beefe, 0x5b81, 0x4b04, { 0x97, 0x53, 0x0d,0x69, 0xb0, 0xdd, 0xaf, 0x5f } },
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings,
        53,
        TRUE,
        },
    },   //  end of dictionary
}; //  end of tempuri_org_xsdLocalDefinitions

const _tempuri_org_xsd tempuri_org_xsd =
{
    {// globalElements
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.Add,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.AddResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYTypeName, // GetAllXY
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllXY,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseTypeName, // GetAllXYResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllXYResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDTypeName, // GetAllArcoBD
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllArcoBD,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseTypeName, // GetAllArcoBDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetAllArcoBDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDTypeName, // GetUtilizadorByID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetUtilizadorByID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDResponseTypeName, // GetUtilizadorByIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetUtilizadorByIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDTypeName, // GetTagsByUserID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetTagsByUserID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseTypeName, // GetTagsByUserIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetTagsByUserIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDTypeName, // GetHumorByUserID
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetHumorByUserID,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDResponseTypeName, // GetHumorByUserIDResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.GetHumorByUserIDResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhoTypeName, // getMenorCaminho
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getMenorCaminho,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhoResponseTypeName, // getMenorCaminhoResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getMenorCaminhoResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getCaminhoForteTypeName, // getCaminhoForte
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getCaminhoForte,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getCaminhoForteResponseTypeName, // getCaminhoForteResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.getCaminhoForteResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWork,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.DoWorkResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._validateLoginTypeName, // validateLogin
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.validateLogin,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._validateLoginResponseTypeName, // validateLoginResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.validateLoginResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumTypeName, // xTagsEmComum
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.xTagsEmComum,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumResponseTypeName, // xTagsEmComumResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.xTagsEmComumResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._tamanhoRedeUtilizadorTypeName, // tamanhoRedeUtilizador
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.tamanhoRedeUtilizador,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._tamanhoRedeUtilizadorResponseTypeName, // tamanhoRedeUtilizadorResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.tamanhoRedeUtilizadorResponse,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._sugereAmigosTypeName, // sugereAmigos
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.sugereAmigos,
        },
        {
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._sugereAmigosResponseTypeName, // sugereAmigosResponse
            (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
            WS_STRUCT_TYPE,
            (void*)&tempuri_org_xsd.externallyReferencedTypes.sugereAmigosResponse,
        },
    }, // globalElements
    {  // begin of externallyReferencedTypes
        {
        sizeof(_Add),
        __alignof(_Add),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._Adddescs._AddFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeName, // Add
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _Add
        {
        sizeof(_AddResponse),
        __alignof(_AddResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._AddResponsedescs._AddResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddResponseTypeName, // AddResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _AddResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYTypeName, // GetAllXY
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllXY
        {
        sizeof(_GetAllXYResponse),
        __alignof(_GetAllXYResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs._GetAllXYResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetAllXYResponsedescs._GetAllXYResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllXYResponseTypeName, // GetAllXYResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllXYResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDTypeName, // GetAllArcoBD
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllArcoBD
        {
        sizeof(_GetAllArcoBDResponse),
        __alignof(_GetAllArcoBDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetAllArcoBDResponsedescs._GetAllArcoBDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetAllArcoBDResponsedescs._GetAllArcoBDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetAllArcoBDResponseTypeName, // GetAllArcoBDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetAllArcoBDResponse
        {
        sizeof(_GetUtilizadorByID),
        __alignof(_GetUtilizadorByID),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDdescs._GetUtilizadorByIDFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDdescs._GetUtilizadorByIDFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDTypeName, // GetUtilizadorByID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetUtilizadorByID
        {
        sizeof(_GetUtilizadorByIDResponse),
        __alignof(_GetUtilizadorByIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDResponsedescs._GetUtilizadorByIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetUtilizadorByIDResponsedescs._GetUtilizadorByIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetUtilizadorByIDResponseTypeName, // GetUtilizadorByIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetUtilizadorByIDResponse
        {
        sizeof(_GetTagsByUserID),
        __alignof(_GetTagsByUserID),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDdescs._GetTagsByUserIDFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDdescs._GetTagsByUserIDFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDTypeName, // GetTagsByUserID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetTagsByUserID
        {
        sizeof(_GetTagsByUserIDResponse),
        __alignof(_GetTagsByUserIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDResponsedescs._GetTagsByUserIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetTagsByUserIDResponsedescs._GetTagsByUserIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetTagsByUserIDResponseTypeName, // GetTagsByUserIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetTagsByUserIDResponse
        {
        sizeof(_GetHumorByUserID),
        __alignof(_GetHumorByUserID),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDdescs._GetHumorByUserIDFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDdescs._GetHumorByUserIDFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDTypeName, // GetHumorByUserID
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetHumorByUserID
        {
        sizeof(_GetHumorByUserIDResponse),
        __alignof(_GetHumorByUserIDResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDResponsedescs._GetHumorByUserIDResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._GetHumorByUserIDResponsedescs._GetHumorByUserIDResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._GetHumorByUserIDResponseTypeName, // GetHumorByUserIDResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _GetHumorByUserIDResponse
        {
        sizeof(_getMenorCaminho),
        __alignof(_getMenorCaminho),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getMenorCaminhodescs._getMenorCaminhoFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getMenorCaminhodescs._getMenorCaminhoFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhoTypeName, // getMenorCaminho
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getMenorCaminho
        {
        sizeof(_getMenorCaminhoResponse),
        __alignof(_getMenorCaminhoResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getMenorCaminhoResponsedescs._getMenorCaminhoResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getMenorCaminhoResponsedescs._getMenorCaminhoResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getMenorCaminhoResponseTypeName, // getMenorCaminhoResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getMenorCaminhoResponse
        {
        sizeof(_getCaminhoForte),
        __alignof(_getCaminhoForte),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getCaminhoFortedescs._getCaminhoForteFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getCaminhoFortedescs._getCaminhoForteFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getCaminhoForteTypeName, // getCaminhoForte
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getCaminhoForte
        {
        sizeof(_getCaminhoForteResponse),
        __alignof(_getCaminhoForteResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._getCaminhoForteResponsedescs._getCaminhoForteResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._getCaminhoForteResponsedescs._getCaminhoForteResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._getCaminhoForteResponseTypeName, // getCaminhoForteResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _getCaminhoForteResponse
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkTypeName, // DoWork
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWork
        {
        0,
        1,
        0,
        0,
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._DoWorkResponseTypeName, // DoWorkResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _DoWorkResponse
        {
        sizeof(_validateLogin),
        __alignof(_validateLogin),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._validateLogindescs._validateLoginFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._validateLogindescs._validateLoginFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._validateLoginTypeName, // validateLogin
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _validateLogin
        {
        sizeof(_validateLoginResponse),
        __alignof(_validateLoginResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._validateLoginResponsedescs._validateLoginResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._validateLoginResponsedescs._validateLoginResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._validateLoginResponseTypeName, // validateLoginResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _validateLoginResponse
        {
        sizeof(_xTagsEmComum),
        __alignof(_xTagsEmComum),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._xTagsEmComumdescs._xTagsEmComumFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._xTagsEmComumdescs._xTagsEmComumFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumTypeName, // xTagsEmComum
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _xTagsEmComum
        {
        sizeof(_xTagsEmComumResponse),
        __alignof(_xTagsEmComumResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._xTagsEmComumResponsedescs._xTagsEmComumResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._xTagsEmComumResponsedescs._xTagsEmComumResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._xTagsEmComumResponseTypeName, // xTagsEmComumResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _xTagsEmComumResponse
        {
        sizeof(_tamanhoRedeUtilizador),
        __alignof(_tamanhoRedeUtilizador),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._tamanhoRedeUtilizadordescs._tamanhoRedeUtilizadorFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._tamanhoRedeUtilizadordescs._tamanhoRedeUtilizadorFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._tamanhoRedeUtilizadorTypeName, // tamanhoRedeUtilizador
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _tamanhoRedeUtilizador
        {
        sizeof(_tamanhoRedeUtilizadorResponse),
        __alignof(_tamanhoRedeUtilizadorResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._tamanhoRedeUtilizadorResponsedescs._tamanhoRedeUtilizadorResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._tamanhoRedeUtilizadorResponsedescs._tamanhoRedeUtilizadorResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._tamanhoRedeUtilizadorResponseTypeName, // tamanhoRedeUtilizadorResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _tamanhoRedeUtilizadorResponse
        {
        sizeof(_sugereAmigos),
        __alignof(_sugereAmigos),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._sugereAmigosdescs._sugereAmigosFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._sugereAmigosdescs._sugereAmigosFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._sugereAmigosTypeName, // sugereAmigos
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _sugereAmigos
        {
        sizeof(_sugereAmigosResponse),
        __alignof(_sugereAmigosResponse),
        (WS_FIELD_DESCRIPTION**)&tempuri_org_xsdLocalDefinitions.globalElements._sugereAmigosResponsedescs._sugereAmigosResponseFields,
        WsCountOf(tempuri_org_xsdLocalDefinitions.globalElements._sugereAmigosResponsedescs._sugereAmigosResponseFields),
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._sugereAmigosResponseTypeName, // sugereAmigosResponse
        (WS_XML_STRING*)&tempuri_org_xsdLocalDefinitions.dictionary.xmlStrings._AddTypeNamespace, // http://tempuri.org/
        0,
        0,
        0,
        },   // end of struct description for _sugereAmigosResponse
    }, // end of externallyReferencedTypes;
}; // end of _tempuri_org_xsd
